# Generated by Django 4.2.4 on 2023-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_detailed_description_pet_donation_reason_and_more'),
        ('account', '0002_user_adopted_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_posted_pets',
            field=models.ManyToManyField(related_name='posted_by_user', to='pets.pet'),
        ),
    ]
