# Generated by Django 4.2.4 on 2023-11-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone_number_user_user_posted_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_posted_pets',
        ),
    ]
