# Generated by Django 4.2.5 on 2023-11-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_adopted_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adopted_pets',
        ),
    ]
