# Generated by Django 4.2.4 on 2023-11-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_detailed_description_pet_donation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
    ]
