# Generated by Django 4.2.4 on 2023-11-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_detailed_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='detailed_description',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='donation_reason',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vaccination',
        ),
    ]
